version: "3.8"

services:
  database:
    image: mongo:latest
    container_name: mongodb
    networks:
      - net
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    restart: on-failure

  devops-api:
    container_name: devops-api
    build:
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: on-failure
    environment:
      MONGO_URL: mongodb://mongodb:27017
      DB_NAME: mydb


networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
