global:
  # Sendgrid SMTP properties.
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'Alertmanager <alertmanager@cosckoya.io>'
  smtp_auth_username: 'apikey'
  smtp_auth_password: ${{secrets.SMTP_API_KEY}}

  receivers:
    - name: 'mail'
      email_configs:
        - to: "admins@mail.me"
          headers:
            Subject: "Alert ({{ .Status }}): {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }})"
          html: |
            Greetings,
            <p>
            You have the following firing alerts:
            <ul>
            {{ range .Alerts }}
            <li>{{.Labels.alertname}} on {{.Labels.instance}}</li>
            <li>Labels:</li>
            <li>{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
            <li>{{ end }}Annotations:</li>
            <li>{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
            <li>{{ end }}---</li>
            {{ end }}
            </ul>
            </p>

  route:
    group_wait: 10s
    group_interval: 5m
    receiver: mail
    repeat_interval: 10s