global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: "devops-api"
    static_configs:
      - targets: [devops-api:3000]